### ISSUE TITLE
ERROR with braces in array of strings

### ISSUE THREAD

**Issue by jmholla** [uiri/toml#114] opened 2017-07-31 21:05 UTC
When parsing an array of strings where strings have open braces, it can fail quietly and return bad data, or eventually throws an error if there are enough open braces in a string. I've attached some examples (It says txt, but it's python code). The last example will throw an exception (It has three open braces).

[toml_bug.txt](https://github.com/uiri/toml/files/1188830/toml_bug.txt)

**Comment by jmholla** [comment] 2017-08-09 22:14
There is a workaround for this. Use unicode characters:
{ : \u007b
} : \u007d

**Comment by sergioschena** [comment] 2017-08-23 12:26
I also have the same problem:

>>> toml.loads(toml.dumps({'list': ["this is an example ${{AVAR\}"]}))
{u'list': []}

**Comment by toejough** [comment] 2017-08-23 14:02
another example:
```python
toml.loads(toml.dumps({"list": ["{thing}"]}))
```
results in `{"list": []}`

**Comment by toejough** [comment] 2017-08-23 14:05
for anyone else struggling with this, https://github.com/avakar/pytoml doesn't have this problem

**Comment by uiri** [comment] 2017-08-23 19:39
I'm having trouble reproducing this in the latest master. Can someone verify that this isn't a duplicate or has otherwise been fixed in the year since the last pip release?

**Comment by jasonwhite** [comment] 2017-08-30 22:19
I can confirm this is fixed in `master`, but not in the `0.9.2` pip release. It would be great to update the pip package even if all the open issues aren't quite fixed. This bug is currently a blocker for me and the other `pytoml` package mentioned above has its own set of problems.

**Comment by uiri** [comment] 2017-09-01 03:33
Closing as a duplicate of #90.

A new pip release is a priority for me right now. Unfortunately, I've just been unable to dedicate as much time to this project as I would like/as I feel it deserves.

**Closed by uiri** 2017-09-01 03:33 UTC
