### ISSUE TITLE
Comments support

### ISSUE THREAD

**Issue by yjqiang** [uiri/toml#222] opened 2018-12-01 15:05 UTC
#77
Maybe we can generate 'key_comment' with 'key', and then we can make it. By the way, Python 3.7 – Dictionaries now ordered.

**Comment by yjqiang** [comment] 2018-12-01 16:02
"Changed in version 3.7: Dictionary order is guaranteed to be insertion order. This behavior was an implementation detail of CPython from 3.6."

**Comment by uiri** [comment] 2018-12-01 20:08
Closing as duplicate of #77

**Closed by uiri** 2018-12-01 20:08 UTC
