### ISSUE TITLE
Multiline string parsing is wrong

### ISSUE THREAD

**Issue by neurocline** [uiri/toml#155] opened 2018-03-12 05:31 UTC
I believe this line in _load_value:

```
        testv = v[1:].split('"')
```

is causing problems when there is a multiline string with quote marks in it. E.g. this simple string causes toml.loads to error with `toml.TomlDecodeError: Stuff after closed string. WTF?`:

```
value = """
this "string" should work
"""
```

Here is my test case:

```
import toml
text = '''value = """\nthis "string" should work\n"""\n'''
parsed_toml = toml.loads(text)
```

I looked in the toml validation suite you mentioned that you were using, and I noticed it didn't have test cases covering multiline strings that would catch this.

If I figure out a fix that doesn't change too much code, I'll send it to you.

**Comment by uiri** [comment] 2018-03-25 23:29
Hi,

Thank you for your bug report! This looks like a duplicate of a bug which I saw reported within #113 which should now be fixed by 65f997f0 in master and 07aaa4d1 in 0.9.X

Please reopen this issue if that fix did not adequately address the bug.

Thanks!

**Closed by uiri** 2018-03-25 23:29 UTC
