### ISSUE TITLE
Parser fails with muti-line literals containing quotes with toml 0.9.4

### ISSUE THREAD

**Issue by cr** [uiri/toml#177] opened 2018-07-27 13:29 UTC
The toml parser fails when multi-line literals contain double quote characters.

Simple test case with *toml==0.9.4* on *python 3.7.0*:

```
❯ cat /tmp/Cargo.toml 
[package]
description = """hello "world" hello"""

❯ python -c 'import toml ; toml.load(open("/tmp/Cargo.toml"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "venv/lib/python3.7/site-packages/toml.py", line 108, in load
    return loads(f.read(), _dict)
  File "venv/lib/python3.7/site-packages/toml.py", line 373, in loads
    multibackslash)
  File "venv/lib/python3.7/site-packages/toml.py", line 478, in _load_line
    value, vtype = _load_value(pair[1], _dict, strictly_valid)
  File "venv/lib/python3.7/site-packages/toml.py", line 608, in _load_value
    raise TomlDecodeError("Stuff after closed string. WTF?")
toml.TomlDecodeError: Stuff after closed string. WTF?
```

**Comment by uiri** [comment] 2018-09-09 02:17
Closing as duplicate of #113

**Closed by uiri** 2018-09-09 02:17 UTC
