### ISSUE TITLE
Indentation and whitespaces are being stripped away in multiline strings

### ISSUE THREAD

**Issue by noqqe** [uiri/toml#71] opened 2017-01-10 12:25 UTC
Hi,

the current implementation of the parser strips away whitespace from all lines using `strip()`.
To reproduce use this snippet:

``` python
import toml

t = '''
foo = """
test
  test
  test2
test3
    test5
    test6
test7
"""
'''

p = toml.loads(t)
print p["foo"]
```

**Acutal Output**

```
test
test
test2
test3
test5
test6
test7
```

**Expected Output**

```
test
  test
  test2
test3
    test5
    test6
test7
```

This violates the `toml` spec (see https://github.com/toml-lang/toml#string)

> Multi-line basic strings are surrounded by three quotation marks on each side and allow newlines. A newline immediately following the opening delimiter will be trimmed. All other whitespace and newline characters remain intact.

furthermore

> A newline immediately following the opening delimiter will be trimmed. All other content between the delimiters is interpreted as-is without modification.

**Comment by uiri** [comment] 2017-01-20 17:40
Closing as a duplicate of #68 
See #69 for discussion on necessary changes to the toml test suite.

**Closed by uiri** 2017-01-20 17:40 UTC
