### ISSUE TITLE
0.9.4 fails to parse local date without time

### ISSUE THREAD

**Issue by alecloudenback** [uiri/toml#189] opened 2018-09-05 21:43 UTC
With a .toml file with the following contents:
```toml
key4 = 1979-05-27
```
calling `toml.load()` fails with the following error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-5e0b774e5955> in <module>()
      1 import toml
      2 
----> 3 toml.load(r'config.toml')

~\Anaconda3\lib\site-packages\toml.py in load(f, _dict)
     86     if isinstance(f, basestring):
     87         with io.open(f, encoding='utf-8') as ffile:
---> 88             return loads(ffile.read(), _dict)
     89     elif isinstance(f, list):
     90         from os import path as op

~\Anaconda3\lib\site-packages\toml.py in loads(s, _dict)
    371         elif "=" in line:
    372             ret = _load_line(line, currentlevel, _dict, multikey,
--> 373                              multibackslash)
    374             if ret is not None:
    375                 multikey, multilinestr, multibackslash = ret

~\Anaconda3\lib\site-packages\toml.py in _load_line(line, currentlevel, _dict, multikey, multibackslash)
    476         multikey = pair[0]
    477     else:
--> 478         value, vtype = _load_value(pair[1], _dict, strictly_valid)
    479     try:
    480         currentlevel[pair[0]]

~\Anaconda3\lib\site-packages\toml.py in _load_value(v, _dict, strictly_valid)
    662             itype = "float"
    663         else:
--> 664             v = int(v)
    665         if neg:
    666             return (0 - v, itype)

ValueError: invalid literal for int() with base 10: '1979-05-27'
```

Version: `3.5.5 |Anaconda custom (64-bit)| (default, Apr  7 2018, 04:52:34) [MSC v.1900 64 bit (AMD64)]`

And toml version 0.9.4:

```
> print(toml.__version__)
0.9.4
```

**Comment by uiri** [comment] 2018-09-06 02:02
Duplicate of #73 

0.9.4 is compliant with version 0.4.0 of the TOML spec which does not have local date without time.

**Closed by uiri** 2018-09-06 02:02 UTC
