### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by moloney** [uiri/toml#143] opened 2017-11-29 22:05 UTC
There is some sort of mismatch in your package meta data.

In a fresh virtualenv:

    $ pip install toml
    Collecting toml
    Installing collected packages: toml
    Successfully installed toml-0.9.3
    $ pip freeze > req.txt
    $ cat req.txt
    toml==0.9.3

Now in a fresh virtualenv, try to reproduce our previous environment:

    $ pip install -r req.txt
    Collecting toml==0.9.3 (from -r req.txt (line 1))
      Could not find a version that satisfies the requirement toml==0.9.3 (from -r req.txt (line 1)) (from versions: 0.6.0, 0.6.5, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.9.2, 0.9.3.1)
    No matching distribution found for toml==0.9.3 (from -r req.txt (line 1))

**Comment by uiri** [comment] 2017-12-08 07:00
This looks like a duplicate of #129 

Solution A: use 0.9.3.1

Solution B: I prep and release a version 0.9.4

**Comment by devjack** [comment] 2017-12-17 05:13
@uiri is there anything I/we can do to help with Solution B? Solution A is playing a little havoc with my CI/requirements scripts.

**Comment by evilplanet** [comment] 2017-12-21 03:16
It would really help if a new version is released. Miserlou/Zappa/#64

**Comment by uiri** [comment] 2017-12-21 06:57
Closed by c30d7b9 in branch `0.9.X`

**Closed by uiri** 2017-12-21 06:57 UTC
