### ISSUE TITLE
Preserve comments

### ISSUE THREAD

**Issue by amjith** [uiri/toml#122] opened 2017-09-07 03:40 UTC
Would it be possible to preserve the comments while reading a toml file and write the comments back while dumping it? 

This would be tremendously useful for tools that manage their config files and write out the toml in an automatic fashion.

**Comment by amjith** [comment] 2017-09-07 03:47
This request is based on [ConfigObj](http://www.voidspace.org.uk/python/configobj.html#initial-comment) which preserves the comments and writes them back out. ConfigObj is a library for handling INI files.

**Comment by uiri** [comment] 2017-09-07 04:17
Thank you for the request. However, this is a duplicate of #77 which is still open. ConfigObj has already been mentioned there too.

**Closed by uiri** 2017-09-07 04:17 UTC
