### ISSUE TITLE
 Invalid result with multi-line character string and line feed

### ISSUE THREAD

**Issue by pashango2** [uiri/toml#80] opened 2017-03-24 11:00 UTC
It looks like a legitimate TOML to me, but a combination of line feed and multiline literal produces incorrect results.

```python
text = """
    lines = '''
    The first newline is
    trimmed in raw strings.
       'All other whitespace'
       is preserved.
    '''
""".strip()

obj = toml.loads(text)
# invalid
#{u'lines': u"    The first newline is\ntrimmed in raw strings.\n'All other whitespa e''       is preserved.\n"}

# valid
#{u'lines': u"    The first newline is\ntrimmed in raw strings.\n'All other whitespace'       is preserved.\n"}
```

It seems that there is a problem with the line feed after quoting in the multiline literal.

toml: 0.9.0
python:2.7

**Comment by uiri** [comment] 2017-04-12 17:35
It looks like this might be a duplicate of #68 (or a related issue with a similar fix).
I will revisit this after that issue is fixed.

**Closed** 2017-04-12 23:37 UTC
Labels: bug
