### ISSUE TITLE
dotted keys don't work

### ISSUE THREAD

**Issue by ed588** [uiri/toml#173] opened 2018-06-25 18:09 UTC
source:
```toml
a.b = 2
```
result:
```
toml.TomlDecodeError: Found invalid character in key name: '.'. Try quoting the key name.
```
example from the toml spec:
![image](https://user-images.githubusercontent.com/19167629/41867515-3aa0f9cc-78ab-11e8-8f58-e9348b694712.png)

**Comment by uiri** [comment] 2018-06-26 01:40
This does not appear to be part of the [v0.4.0 spec](https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.4.0.md)

**Comment by uiri** [comment] 2018-06-26 01:41
Closing as duplicate of #163

**Closed by uiri** 2018-06-26 01:41 UTC
Labels: 1.0
