### ISSUE TITLE
Exception with keys with embedded ='s in string

### ISSUE THREAD

**Issue by vvuk** [uiri/toml#61] opened 2016-08-12 21:00 UTC
The following toml:
```
[foo]
"checksum browserhtml 0.1.15 (git+https://github.com/browserhtml/browserhtml?branch=gh-pages)" = "<none>"
```
raises the following exception when parsed with toml.py:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "toml.py", line 298, in loads
    if load_date(pair[-1]) != None:
  File "toml.py", line 350, in load_date
    tz = TomlTz(val[19:24])
  File "toml.py", line 9, in __new__
    self._hours = int(toml_offset[:3])
```
To reproduce:
```
import toml
toml.loads("[foo]\n\"checksum browserhtml 0.1.15 (git+https://github.com/browserhtml/browserhtml?branch=gh-pages)\" = \"<none>\"\n")
```

**Comment by uiri** [comment] 2016-08-31 20:22
I could not reproduce this issue on the latest master (which is also version 0.9.2). What version are you running?

**Comment by uiri** [comment] 2016-10-28 05:41
Closing as fixed.

**Closed by uiri** 2016-10-28 05:41 UTC
