### ISSUE TITLE
Subkeys are not dumped together

### ISSUE THREAD

**Issue by xNinjaKittyx** [uiri/toml#221] opened 2018-11-19 19:52 UTC
This may not actually be a bug, but it would be convenient if the parent keys were grouped together.

Instead of 
```
[vwefoin.sfxsfx]
ip = "8.8.8.8"

[mxvin.mxvin_1]
key = "value"

[mxvin.mxvin_2]
key = "value"

[mxvin.mxvin_3]
key = "value"

[mxvin.mxvin_4]
key = "value"

[vwefoin.sfxsfx.memes]
obiwan = "hello there"
```

It should dump like this:
```
[vwefoin.sfxsfx]
ip = "8.8.8.8"

[vwefoin.sfxsfx.memes]
obiwan = "hello there"

[mxvin.mxvin_1]
key = "value"

[mxvin.mxvin_2]
key = "value"

[mxvin.mxvin_3]
key = "value"

[mxvin.mxvin_4]
key = "value"
```

If previous behavior is also desirable, perhaps support different sorting policies?

**Comment by uiri** [comment] 2018-11-20 02:29
From your explanation, this looks like a duplicate of #88

Feel free to reopen if you think I've misunderstood the issue.

**Closed by uiri** 2018-11-20 02:29 UTC
