### ISSUE TITLE
version 0.9.3 not able to read a list of empty strings?

### ISSUE THREAD

**Issue by dirkphilip** [uiri/toml#140] opened 2017-11-07 12:43 UTC
Since version 0.9.3, a toml file like this:

[settings]
priorities = ["", "N"]

produces an error message when trying to load the toml file (with python 3.6) It seems to be caused by
the empty string

**Comment by adamrjd** [comment] 2017-11-20 21:44
Also running into this issue. Here's the trace

`Traceback (most recent call last):
  File "c:\Users\adam.r.dornford\OneDrive - Accenture\__INTERNAL\_proj\codesitespy\sandbox.py", line 4, in <module>
    t = load(f)
  File "C:\Users\adam.r.dornford\AppData\Local\Programs\Python\Python36-32\lib\site-packages\toml.py", line 108, in load
    return loads(f.read(), _dict)
  File "C:\Users\adam.r.dornford\AppData\Local\Programs\Python\Python36-32\lib\site-packages\toml.py", line 373, in loads
    multibackslash)
  File "C:\Users\adam.r.dornford\AppData\Local\Programs\Python\Python36-32\lib\site-packages\toml.py", line 478, in _load_line
    value, vtype = _load_value(pair[1], _dict, strictly_valid)
  File "C:\Users\adam.r.dornford\AppData\Local\Programs\Python\Python36-32\lib\site-packages\toml.py", line 637, in _load_value
    return (_load_array(v, _dict), "array")
  File "C:\Users\adam.r.dornford\AppData\Local\Programs\Python\Python36-32\lib\site-packages\toml.py", line 715, in _load_array
    while ab[-1] != ab[0] or (ab[0] == ab[1] == ab[2] and
IndexError: string index out of range
`

Not really sure what the _load_array function is doing with string arrays but that's where the issue is.

**Comment by uiri** [comment] 2018-03-24 07:09
Thanks to both of you for your bug reports!

This should have been fixed by 46f83c19 which was part of release 0.9.4

Closing as a duplicate of #133; please re-open this issue if you feel that the bug still persists in 0.9.4.

**Closed by uiri** 2018-03-24 07:09 UTC
