### ISSUE TITLE
How to dump list so a new-line character is added between elements?

### ISSUE THREAD

**Issue by GlenNicholls** [uiri/toml#323] opened 2020-10-13 19:50 UTC
Currently when using the TOML encoder, I see the following dump:

```
[libraries.something]
files = [ "support/common/firmware_dsp-trunk/firmware/src/IntAndDump/src/IntegrateAndDumpPkg.vhd", "support/common/firmware_dsp-trunk/firmware/src/IntAndDump/src/IntegrateAndDumpWithStrobe.vhd", "support/common/firmware_dsp-trunk/firmware/src/Loops/src/LoopsPkg.vhd", ]
```

Is there a way to configure the dumping so it is more readable? E.g. allow new lines between list elements to produce

```
[libraries.something]
files = [ 
    "support/common/firmware_dsp-trunk/firmware/src/IntAndDump/src/IntegrateAndDumpPkg.vhd", 
    "support/common/firmware_dsp-trunk/firmware/src/IntAndDump/src/IntegrateAndDumpWithStrobe.vhd", 
    "support/common/firmware_dsp-trunk/firmware/src/Loops/src/LoopsPkg.vhd", 
]
```

**Comment by pradyunsg** [comment] 2022-04-20 18:34
Closing as a duplicate of #311.

**Closed by pradyunsg** 2022-04-20 18:34 UTC
Labels: component: encoder, resolution: duplicate
