### ISSUE TITLE
float resolves to datetime on load

### ISSUE THREAD

**Issue by lawrencey99** [uiri/toml#194] opened 2018-09-11 01:16 UTC
>>> toml.loads('z = 3853110.0341112586')
{'z': datetime.datetime(3853, 10, 3, 11, 25, 6)}

https://github.com/uiri/toml/blob/a444a3659ea06d62fa3aeac9595946ebcbec13ae/toml/decoder.py#L498

Should probably check if works as other types first, or if the separators between YYYY MM DD etc. are also numbers. If they are numbers, probably not a datetime.

**Comment by uiri** [comment] 2018-09-11 01:42
Hi Lawrence,

Thank you for reporting this.

Which TOML version are you running?

Have you checked out the linked commit and run `python setup.py install` ?

This looks like a duplicate of #149 which was fixed in eb2d6687

**Closed** 2018-10-02 02:08 UTC
