### ISSUE TITLE
Multi-line basic string trims empty lines

### ISSUE THREAD

**Issue by condemil** [uiri/toml#124] opened 2017-09-10 21:46 UTC
From spec:

> Multi-line basic strings are surrounded by three quotation marks on each side and allow newlines. A newline immediately following the opening delimiter will be trimmed. All other whitespace and newline characters remain intact.

Test toml:

```
str1 = """
Roses are red

Violets are blue"""
```

Result:

```
>>> toml.load('test.toml')['str1']
'Roses are red\nViolets are blue'
```

Expected result:

```
>>> toml.load('test.toml')['str1']
'Roses are red\n\nViolets are blue'
```

**Comment by uiri** [comment] 2017-09-11 04:18
Hi,

Thank you for the bug report.

Can you provide enough information so that I can ascertain whether this is a duplicate of #113, #123,  #119, #116, #80, or #68 ?

Closing as duplicate.

**Closed by uiri** 2017-09-11 04:18 UTC
